/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Computer/computer_setup.glb -o src/components/canvas/ComputerSetup.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ScreenUI } from './ScreenUI'
import { useControls } from 'leva'

type GLTFResult = GLTF & {
  nodes: {
    monitor_base: THREE.Mesh
    computer: THREE.Mesh
    keyboard: THREE.Mesh
    mouse: THREE.Mesh
    cables: THREE.Mesh
  }
  materials: {}
  animations: THREE.AnimationClip[]
}

type Props = React.JSX.IntrinsicElements['group'] & {
  onTransitionComplete?: () => void
}

export function Model({ onTransitionComplete, ...props }: Props) {
  const { nodes, materials } = useGLTF('/models/Computer/computer_setup.glb') as unknown as GLTFResult
  
  // Expose controls to the user so they can perfectly tune the screen placement!
  const screenTransform = useControls('Screen Position', {
    x: { value: 0, step: 0.01 },
    y: { value: 1.15, step: 0.01 },
    z: { value: -0.4, step: 0.01 },
    rx: { value: -0.1, step: 0.01 },
    ry: { value: 0, step: 0.01 },
    rz: { value: 0, step: 0.01 },
    scale: { value: 0.1, step: 0.01, min: 0.01, max: 0.5 },
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.monitor_base.geometry} material={nodes.monitor_base.material} />
      <mesh geometry={nodes.computer.geometry} material={nodes.computer.material}>
        <Html 
          transform 
          occlude 
          position={[screenTransform.x, screenTransform.y, screenTransform.z]} 
          rotation={[screenTransform.rx, screenTransform.ry, screenTransform.rz]} 
          scale={screenTransform.scale} 
          distanceFactor={1.5} 
          wrapperClass="htmlScreen"
        >
          <ScreenUI onEnter={onTransitionComplete!} isEntering={false} />
        </Html>
      </mesh>
      <mesh geometry={nodes.keyboard.geometry} material={nodes.keyboard.material} />
      <mesh geometry={nodes.mouse.geometry} material={nodes.mouse.material} />
      <mesh geometry={nodes.cables.geometry} material={nodes.cables.material} />
    </group>
  )
}

useGLTF.preload('/models/Computer/computer_setup.glb')
