/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Decor/decor.glb -o src/components/canvas/DecorModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    binder_1: THREE.Mesh
    coffee: THREE.Mesh
    paper: THREE.Mesh
    paper_holder_bottom: THREE.Mesh
    paper_stack_1: THREE.Mesh
    paper_stack_2: THREE.Mesh
    plant: THREE.Mesh
    paper_holder_top: THREE.Mesh
    binder_2: THREE.Mesh
  }
  materials: {}
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Decor/decor.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.binder_1.geometry} material={nodes.binder_1.material} />
      <mesh geometry={nodes.coffee.geometry} material={nodes.coffee.material} />
      <mesh geometry={nodes.paper.geometry} material={nodes.paper.material} />
      <mesh geometry={nodes.paper_holder_bottom.geometry} material={nodes.paper_holder_bottom.material} />
      <mesh geometry={nodes.paper_stack_1.geometry} material={nodes.paper_stack_1.material} />
      <mesh geometry={nodes.paper_stack_2.geometry} material={nodes.paper_stack_2.material} />
      <mesh geometry={nodes.plant.geometry} material={nodes.plant.material} />
      <mesh geometry={nodes.paper_holder_top.geometry} material={nodes.paper_holder_top.material} />
      <mesh geometry={nodes.binder_2.geometry} material={nodes.binder_2.material} />
    </group>
  )
}

useGLTF.preload('/models/Decor/decor.glb')
