/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/World/environment.glb -o src/components/canvas/EnvironmentModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Background: THREE.Mesh
    desk: THREE.Mesh
    chair_base: THREE.Mesh
    chair_seat: THREE.Mesh
  }
  materials: {}
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/World/environment.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Background.geometry} material={nodes.Background.material} />
      <mesh geometry={nodes.desk.geometry} material={nodes.desk.material} />
      <mesh geometry={nodes.chair_base.geometry} material={nodes.chair_base.material} />
      <mesh geometry={nodes.chair_seat.geometry} material={nodes.chair_seat.material} />
    </group>
  )
}

useGLTF.preload('/models/World/environment.glb')
